#!/usr/bin/env python3
"""Generate a normalized simulator profile and Makefile fragment."""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
from pathlib import Path


TOP_KEYS = {
    "schema_version", "name", "simulator", "version", "status",
    "compile_tokens", "run_tokens", "environment_keys", "capabilities",
    "evidence_paths",
}
SIMULATORS = {"vcs", "questa", "xcelium", "verilator", "custom"}
PLACEHOLDERS = {"filelist", "top", "binary", "seed", "test"}
IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_-]*")
ENV_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
SECRET_RE = re.compile(r"(?i)(password|passwd|secret|token|license[_-]?(?:file|server)?|\d+@[^/\s]+)")
PLACEHOLDER_RE = re.compile(r"\{([^{}]+)\}")


def fail(message: str) -> None:
    raise SystemExit(f"ERROR: {message}")


def validate_tokens(tokens: object, where: str) -> list[str]:
    if not isinstance(tokens, list) or not all(isinstance(item, str) and item for item in tokens):
        fail(f"{where} must be a list of non-empty strings")
    result: list[str] = []
    for token in tokens:
        if "\n" in token or "\r" in token or "\x00" in token:
            fail(f"{where} contains a control character")
        if Path(token).is_absolute():
            fail(f"{where} contains an absolute path: {token}")
        unknown = set(PLACEHOLDER_RE.findall(token)) - PLACEHOLDERS
        if unknown:
            fail(f"{where} contains unsupported placeholders: {sorted(unknown)}")
        if SECRET_RE.search(token):
            fail(f"{where} contains secret-looking material")
        result.append(token)
    return result


def validate(spec: object) -> dict:
    if not isinstance(spec, dict):
        fail("top level must be an object")
    unknown = set(spec) - TOP_KEYS
    missing = TOP_KEYS - set(spec)
    if unknown or missing:
        fail(f"top-level keys unknown={sorted(unknown)} missing={sorted(missing)}")
    if spec["schema_version"] != 1:
        fail("schema_version must be 1")
    if not isinstance(spec["name"], str) or not IDENT.fullmatch(spec["name"]):
        fail("name must be a safe identifier")
    if spec["simulator"] not in SIMULATORS:
        fail(f"simulator must be one of {sorted(SIMULATORS)}")
    if not isinstance(spec["version"], str) or not spec["version"].strip():
        fail("version must be a non-empty reviewed string")
    if spec["status"] != "configured":
        fail("status must be 'configured'; testing/support require external evidence")
    compile_tokens = validate_tokens(spec["compile_tokens"], "compile_tokens")
    run_tokens = validate_tokens(spec["run_tokens"], "run_tokens")
    if not compile_tokens:
        fail("compile_tokens must not be empty")
    env = spec["environment_keys"]
    if not isinstance(env, list) or not all(isinstance(item, str) and ENV_IDENT.fullmatch(item) for item in env):
        fail("environment_keys must contain variable names only")
    if len(env) != len(set(env)):
        fail("environment_keys contains duplicates")
    for key in ("capabilities", "evidence_paths"):
        value = spec[key]
        if not isinstance(value, list) or not all(isinstance(item, str) and item.strip() for item in value):
            fail(f"{key} must be a list of non-empty strings")
        if len(value) != len(set(value)):
            fail(f"{key} contains duplicates")
    for path in spec["evidence_paths"]:
        if Path(path).is_absolute() or ".." in Path(path).parts:
            fail(f"evidence path must be project-relative: {path}")
    normalized = dict(spec)
    normalized["compile_tokens"] = compile_tokens
    normalized["run_tokens"] = run_tokens
    normalized["capabilities"] = sorted(spec["capabilities"])
    normalized["evidence_paths"] = sorted(spec["evidence_paths"])
    return normalized


def makefile(spec: dict) -> str:
    compile_cmd = " ".join(shlex.quote(token) for token in spec["compile_tokens"])
    run_cmd = " ".join(shlex.quote(token) for token in spec["run_tokens"])
    env = " ".join(spec["environment_keys"])
    return (
        "# Generated by verif-harness add-simulator-profile.\n"
        "# Status is CONFIGURED; real tool evidence is required for support.\n"
        f"SIM_PROFILE_NAME := {spec['name']}\n"
        f"SIM_PROVIDER := {spec['simulator']}\n"
        f"SIM_VERSION_CONTRACT := {spec['version']}\n"
        f"SIM_REQUIRED_ENV := {env}\n"
        f"SIM_COMPILE := {compile_cmd}\n"
        f"SIM_RUN := {run_cmd}\n"
    )


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    temp.write_text(content, encoding="utf-8")
    os.replace(temp, path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, required=True)
    parser.add_argument("--profile-out", type=Path, required=True)
    parser.add_argument("--make-out", type=Path, required=True)
    args = parser.parse_args()
    for output in (args.profile_out, args.make_out):
        if output.exists():
            fail(f"refusing to overwrite: {output}")
    spec = validate(json.loads(args.spec.read_text(encoding="utf-8")))
    profile = json.dumps(spec, indent=2, sort_keys=True) + "\n"
    fragment = makefile(spec)
    atomic_write(args.profile_out, profile)
    atomic_write(args.make_out, fragment)
    print(args.profile_out)
    print(args.make_out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
