#!/usr/bin/env python3
"""Install and configure the managed xverif MCP source without secrets."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


TOOLS = ["xbit", "xentry", "xloc", "xsva", "xcov", "xdebug", "xwaveform"]
PROFILE_RELATIVE = Path(".harness/mcp/xverif.json")
PROFILE_KEYS = {
    "schema_version", "server_id", "runtime", "transport", "backend", "source",
    "source_commit", "required_tools", "environment_keys", "registration",
    "registration_path", "launcher",
}
LEGACY_PROFILE_KEYS = PROFILE_KEYS - {"registration_path", "launcher"}
PACKAGE_ROOT = Path(__file__).resolve().parents[4]
LAUNCHER_RELATIVE = Path(".harness/mcp/xverif-mcp")
CODEX_CONFIG_RELATIVE = Path(".codex/config.toml")
KIMI_CONFIG_RELATIVE = Path(".kimi-code/mcp.json")
CODEX_BLOCK_BEGIN = "# BEGIN verif-harness managed xverif MCP"
CODEX_BLOCK_END = "# END verif-harness managed xverif MCP"
INHERITED_ENVIRONMENT_KEYS = [
    "VERDI_HOME", "LD_LIBRARY_PATH", "PATH",
    "XVERIF_MCP_STARTUP_TIMEOUT_SEC", "XVERIF_MCP_REQUEST_TIMEOUT_SEC",
    "XDEBUG_SESSION_START_TIMEOUT_SEC", "XDEBUG_SESSION_IDLE_TIMEOUT_SEC",
]


def fail(message: str) -> None:
    raise SystemExit(f"ERROR: {message}")


def dependency_root(project_root: Path) -> Path:
    """Locate the package checkout while preserving the in-tree legacy layout."""
    if (project_root / "scripts/setup_xverif.py").is_file() and (
        project_root / "deps/xverif.lock.json"
    ).is_file():
        return project_root
    return PACKAGE_ROOT


def managed_state(project_root: Path) -> dict[str, Any]:
    package_root = dependency_root(project_root)
    result = subprocess.run(
        [
            sys.executable,
            str(package_root / "scripts/setup_xverif.py"),
            "--project-root",
            str(package_root),
            "--check",
            "--json",
        ],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError:
        payload = {"state": "BLOCKED", "blockers": [result.stderr.strip() or result.stdout.strip()]}
    payload["returncode"] = result.returncode
    return payload


def profile_path(project_root: Path, raw: Path | None) -> Path:
    path = raw or (project_root / PROFILE_RELATIVE)
    path = path if path.is_absolute() else project_root / path
    path = path.resolve()
    if project_root != path and project_root not in path.parents:
        fail("MCP profile must remain under project root")
    return path


def atomic_write(path: Path, content: str, executable: bool = False) -> None:
    if path.is_symlink():
        fail(f"refusing to replace symlink: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        if executable:
            temporary.chmod(0o755)
        os.replace(temporary, path)
    finally:
        if temporary.is_file():
            temporary.unlink()


def launcher_content(backend: str) -> str:
    return "\n".join([
        "#!/usr/bin/env bash",
        "# Generated by verif-harness; contains no credentials.",
        "set -euo pipefail",
        'mcp_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        'mcp_workspace_root="$(cd "$mcp_script_dir/../.." && pwd)"',
        'mcp_package_root=""',
        'if [[ -x "$mcp_workspace_root/scripts/setup_managed.sh" ]]; then',
        '  mcp_package_root="$mcp_workspace_root"',
        'elif [[ -d "$mcp_workspace_root/.agents/skills/verif-harness" ]]; then',
        '  mcp_skill_root="$(cd -P "$mcp_workspace_root/.agents/skills/verif-harness" && pwd)"',
        '  mcp_package_root="$(cd "$mcp_skill_root/../.." && pwd)"',
        'elif [[ -d "$mcp_workspace_root/.kimi-code/skills/verif-harness" ]]; then',
        '  mcp_skill_root="$(cd -P "$mcp_workspace_root/.kimi-code/skills/verif-harness" && pwd)"',
        '  mcp_package_root="$(cd "$mcp_skill_root/../.." && pwd)"',
        "else",
        '  echo "ERROR: cannot resolve the verif-harness package from this workspace" >&2',
        "  exit 2",
        "fi",
        'mcp_xverif_root="$mcp_package_root/.deps/xverif"',
        'mcp_python="$mcp_package_root/.deps/runtime/venv/bin/python"',
        'mcp_upstream_launcher="$mcp_xverif_root/tools/xverif-mcp"',
        'if [[ ! -x "$mcp_python" || ! -x "$mcp_upstream_launcher" ]]; then',
        '  echo "ERROR: managed xverif MCP runtime is incomplete; rerun setup" >&2',
        "  exit 2",
        "fi",
        'export XVERIF_HOME="$mcp_xverif_root"',
        'export PYTHON="$mcp_python"',
        'export PYTHONPATH="$mcp_xverif_root/xverif_mcp/src:$mcp_xverif_root"',
        f'export XVERIF_MCP_BACKEND="{backend}"',
        'exec "$mcp_upstream_launcher" "$@"',
        "",
    ])


def install_project_launcher(
    project_root: Path, backend: str,
) -> Path:
    target = project_root / LAUNCHER_RELATIVE
    expected = launcher_content(backend)
    if target.is_file():
        observed = target.read_text(encoding="utf-8")
        if observed == expected and os.access(target, os.X_OK):
            return target
        if not observed.startswith(
            "#!/usr/bin/env bash\n# Generated by verif-harness; contains no credentials.\n"
        ):
            fail(f"refusing to overwrite unmanaged MCP launcher: {target}")
    elif target.exists():
        fail(f"MCP launcher path is not a regular file: {target}")
    atomic_write(target, expected, executable=True)
    return target


def expected_codex_server() -> dict[str, Any]:
    return {
        "command": LAUNCHER_RELATIVE.as_posix(),
        "args": [],
        "cwd": ".",
        "required": True,
        "startup_timeout_sec": 30,
        "tool_timeout_sec": 300,
        "env_vars": INHERITED_ENVIRONMENT_KEYS,
    }


def codex_block() -> str:
    server = expected_codex_server()
    environment = ", ".join(json.dumps(key) for key in server["env_vars"])
    return "\n".join([
        CODEX_BLOCK_BEGIN,
        "[mcp_servers.xverif]",
        f"command = {json.dumps(server['command'])}",
        "args = []",
        f"cwd = {json.dumps(server['cwd'])}",
        "required = true",
        f"startup_timeout_sec = {server['startup_timeout_sec']}",
        f"tool_timeout_sec = {server['tool_timeout_sec']}",
        f"env_vars = [{environment}]",
        CODEX_BLOCK_END,
    ])


def register_codex(project_root: Path) -> Path:
    target = project_root / CODEX_CONFIG_RELATIVE
    if target.is_symlink():
        fail(f"refusing to follow Codex config symlink: {target}")
    existing = target.read_text(encoding="utf-8") if target.is_file() else ""
    block = codex_block()
    has_begin = CODEX_BLOCK_BEGIN in existing
    has_end = CODEX_BLOCK_END in existing
    if has_begin != has_end:
        fail("Codex xverif MCP managed block is partial")
    if has_begin:
        if existing.count(CODEX_BLOCK_BEGIN) != 1 or existing.count(CODEX_BLOCK_END) != 1:
            fail("Codex xverif MCP managed block is duplicated")
        if block not in existing:
            fail("existing Codex xverif MCP registration conflicts with setup")
        return target
    if re.search(r'(?m)^\s*\[\s*mcp_servers\.(?:xverif|"xverif")\s*\]\s*$', existing):
        fail("existing Codex xverif MCP registration conflicts with setup")
    separator = "" if not existing else ("\n" if existing.endswith("\n") else "\n\n")
    atomic_write(target, existing + separator + block + "\n")
    return target


def expected_kimi_server() -> dict[str, Any]:
    return {
        "command": LAUNCHER_RELATIVE.as_posix(),
        "args": [],
        "cwd": ".",
        "enabled": True,
        "startupTimeoutMs": 30000,
        "toolTimeoutMs": 300000,
    }


def register_kimi(project_root: Path) -> Path:
    target = project_root / KIMI_CONFIG_RELATIVE
    if target.is_symlink():
        fail(f"refusing to follow Kimi MCP config symlink: {target}")
    if target.is_file():
        try:
            value = json.loads(target.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            fail(f"cannot register xverif in invalid Kimi MCP config: {exc}")
    else:
        value = {"mcpServers": {}}
    if not isinstance(value, dict) or not isinstance(value.get("mcpServers"), dict):
        fail("Kimi MCP config must contain an mcpServers object")
    expected = expected_kimi_server()
    observed = value["mcpServers"].get("xverif")
    if observed is not None:
        if observed != expected:
            fail("existing Kimi xverif MCP registration conflicts with setup")
        return target
    value["mcpServers"]["xverif"] = expected
    atomic_write(target, json.dumps(value, indent=2, sort_keys=True) + "\n")
    return target


def validate_runtime_registration(project_root: Path, profile: dict[str, Any]) -> list[str]:
    blockers: list[str] = []
    launcher = project_root / profile["launcher"]
    if not launcher.is_file() or not os.access(launcher, os.X_OK):
        blockers.append(f"project MCP launcher missing or not executable: {launcher}")
    registration = project_root / profile["registration_path"]
    if profile["runtime"] == "codex":
        try:
            observed = registration.read_text(encoding="utf-8")
        except OSError:
            observed = ""
        if codex_block() not in observed:
            blockers.append("Codex project xverif MCP registration is missing or has drifted")
    else:
        try:
            parsed = json.loads(registration.read_text(encoding="utf-8"))
            observed = parsed.get("mcpServers", {}).get("xverif")
        except (OSError, json.JSONDecodeError):
            observed = None
        if observed != expected_kimi_server():
            blockers.append("Kimi project xverif MCP registration is missing or has drifted")
    return blockers


def validate_profile(value: Any, lock_commit: str | None = None) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != PROFILE_KEYS:
        fail(f"MCP profile keys must be exactly {sorted(PROFILE_KEYS)}")
    if value["schema_version"] != 1:
        fail("MCP profile schema_version must be 1")
    if value["server_id"] != "xverif":
        fail("MCP profile server_id must be xverif")
    if value["runtime"] not in {"codex", "kimi"}:
        fail("MCP profile runtime must be codex or kimi")
    if value["transport"] != "stdio":
        fail("xverif MCP currently supports only stdio transport")
    if value["backend"] not in {"direct", "lsf"}:
        fail("MCP backend must be direct or lsf")
    if value["source"] != "managed-xverif-checkout":
        fail("MCP source must be managed-xverif-checkout")
    if not isinstance(value["source_commit"], str) or len(value["source_commit"]) != 40:
        fail("MCP source_commit must be a full Git object ID")
    if lock_commit is not None and value["source_commit"] != lock_commit:
        fail("MCP source_commit does not match deps/xverif.lock.json")
    if value["required_tools"] != TOOLS:
        fail(f"MCP required_tools must match {TOOLS}")
    keys = value["environment_keys"]
    if not isinstance(keys, list) or not all(isinstance(key, str) and key for key in keys):
        fail("environment_keys must contain names only")
    if len(keys) != len(set(keys)):
        fail("environment_keys contains duplicates")
    if value["registration"] != "project-managed":
        fail("MCP registration must be project-managed")
    expected_registration = (
        CODEX_CONFIG_RELATIVE if value["runtime"] == "codex" else KIMI_CONFIG_RELATIVE
    ).as_posix()
    if value["registration_path"] != expected_registration:
        fail("MCP registration_path differs from the selected runtime")
    if value["launcher"] != LAUNCHER_RELATIVE.as_posix():
        fail("MCP launcher differs from the project-managed path")
    return value


def legacy_profile_matches(value: Any, expected: dict[str, Any]) -> bool:
    if not isinstance(value, dict) or set(value) != LEGACY_PROFILE_KEYS:
        return False
    comparable = {
        key: expected[key] for key in LEGACY_PROFILE_KEYS if key != "registration"
    }
    return (
        value.get("registration") == "host-managed"
        and {key: value.get(key) for key in comparable} == comparable
    )


def lock_commit(project_root: Path) -> str:
    package_root = dependency_root(project_root)
    try:
        lock = json.loads((package_root / "deps/xverif.lock.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read xverif lock: {exc}")
    commit = lock.get("commit")
    if not isinstance(commit, str):
        fail("xverif lock does not contain a commit")
    return commit


def configure(args: argparse.Namespace) -> int:
    project_root = args.project_root.resolve()
    target = profile_path(project_root, args.profile)
    managed = managed_state(project_root)
    if managed.get("state") not in {"READY", "INSTALLED"}:
        fail("managed xverif source is not ready; run 'xverif mcp install' first")
    commit = lock_commit(project_root)
    registration_path = (
        CODEX_CONFIG_RELATIVE if args.runtime == "codex" else KIMI_CONFIG_RELATIVE
    )
    profile = {
        "schema_version": 1,
        "server_id": "xverif",
        "runtime": args.runtime,
        "transport": "stdio",
        "backend": args.backend,
        "source": "managed-xverif-checkout",
        "source_commit": commit,
        "required_tools": TOOLS,
        "environment_keys": [
            "XVERIF_HOME", "XVERIF_MCP_BACKEND", "VERDI_HOME",
            "LD_LIBRARY_PATH", "PATH", "XVERIF_MCP_STARTUP_TIMEOUT_SEC",
            "XVERIF_MCP_REQUEST_TIMEOUT_SEC", "XDEBUG_SESSION_START_TIMEOUT_SEC",
            "XDEBUG_SESSION_IDLE_TIMEOUT_SEC",
        ],
        "registration": "project-managed",
        "registration_path": registration_path.as_posix(),
        "launcher": LAUNCHER_RELATIVE.as_posix(),
    }
    if target.is_file():
        try:
            existing_value = json.loads(target.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            fail(f"refusing to overwrite unreadable MCP profile: {exc}")
        try:
            validate_profile(existing_value, commit)
        except SystemExit as exc:
            if not legacy_profile_matches(existing_value, profile):
                fail(f"refusing to overwrite invalid MCP profile: {exc}")
    elif target.exists():
        fail(f"MCP profile path is not a regular file: {target}")
    install_project_launcher(project_root, args.backend)
    registration = (
        register_codex(project_root)
        if args.runtime == "codex"
        else register_kimi(project_root)
    )
    existing_profile = (
        json.loads(target.read_text(encoding="utf-8")) if target.is_file() else None
    )
    if existing_profile != profile:
        atomic_write(target, json.dumps(profile, indent=2, sort_keys=True) + "\n")
    print(json.dumps({
        "state": "CONFIGURED",
        "profile": str(target),
        "registration": str(registration),
        "launcher": str(project_root / LAUNCHER_RELATIVE),
        "profile_data": profile,
    }, indent=2, sort_keys=True))
    return 0


def status(args: argparse.Namespace) -> int:
    project_root = args.project_root.resolve()
    target = profile_path(project_root, args.profile)
    managed = managed_state(project_root)
    payload: dict[str, Any] = {
        "schema_version": 1,
        "state": "UNCONFIGURED",
        "profile": str(target),
        "managed_xverif": managed,
        "runtime_registration": "project-managed",
        "notice": "This command validates project-local MCP registration only; user-level settings remain unchanged.",
    }
    if not target.is_file():
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 1
    try:
        profile = json.loads(target.read_text(encoding="utf-8"))
        profile = validate_profile(profile, lock_commit(project_root))
    except (OSError, json.JSONDecodeError, SystemExit) as exc:
        payload["state"] = "BLOCKED"
        payload["blockers"] = [str(exc)]
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 1
    payload["profile_data"] = profile
    if managed.get("state") not in {"READY", "INSTALLED"}:
        payload["state"] = "BLOCKED"
        payload["blockers"] = managed.get("blockers", ["managed xverif is unavailable"])
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 1
    registration_blockers = validate_runtime_registration(project_root, profile)
    if registration_blockers:
        payload["state"] = "BLOCKED"
        payload["blockers"] = registration_blockers
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 1
    python_executable = args.python or Path(sys.executable)
    sdk_check = subprocess.run(
        [str(python_executable), "-c", "import importlib.util; raise SystemExit(0 if importlib.util.find_spec('mcp') else 1)"],
        check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    sdk_available = sdk_check.returncode == 0
    payload["python"] = str(python_executable)
    payload["mcp_sdk_available"] = sdk_available
    payload["state"] = "READY_FOR_RUNTIME_PROBE" if sdk_available else "MCP_SDK_MISSING"
    if not sdk_available:
        payload["blockers"] = [
            "install the separately managed Python dependency mcp[cli] in the runtime environment (setup.sh installs it by default)"
        ]
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0 if sdk_available else 1


def install(args: argparse.Namespace) -> int:
    project_root = args.project_root.resolve()
    package_root = dependency_root(project_root)
    result = subprocess.run(
        [sys.executable, str(package_root / "scripts/setup_xverif.py"), "--project-root", str(package_root), "--json"],
        check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
    )
    if result.stdout:
        print(result.stdout, end="")
    if result.returncode != 0:
        if result.stderr:
            print(result.stderr, end="", file=sys.stderr)
        return result.returncode
    print(json.dumps({
        "state": "INSTALLED_SOURCE",
        "notice": "xverif_mcp source and launcher are installed; setup.sh installs the separately managed mcp[cli] dependency by default.",
    }, indent=2, sort_keys=True))
    return 0


def probe(args: argparse.Namespace) -> int:
    payload = {
        "state": "RUNTIME_PROBE_REQUIRED",
        "server": "xverif",
        "tool": "xverif_ping",
        "profile": str(profile_path(args.project_root.resolve(), args.profile)),
        "notice": "Run xverif_ping through the configured Codex/Kimi MCP runtime; static CLI checks cannot prove MCP protocol availability.",
    }
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    for name in ("install", "status", "configure", "probe"):
        command = commands.add_parser(name)
        command.add_argument("--project-root", type=Path, default=Path.cwd())
        command.add_argument("--profile", type=Path)
    commands.choices["configure"].add_argument("--runtime", choices=("codex", "kimi"), required=True)
    commands.choices["configure"].add_argument("--backend", choices=("direct", "lsf"), default="direct")
    commands.choices["status"].add_argument("--python", type=Path)
    args = parser.parse_args()
    if args.command == "install":
        return install(args)
    if args.command == "configure":
        return configure(args)
    if args.command == "status":
        return status(args)
    return probe(args)


if __name__ == "__main__":
    raise SystemExit(main())
